
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 33;
  public static final int OSB = 23;
  public static final int GE = 13;
  public static final int UMINUS = 42;
  public static final int LPAREN = 43;
  public static final int SEMI = 40;
  public static final int INT = 8;
  public static final int MINUS = 31;
  public static final int STAR = 34;
  public static final int RPAREN = 44;
  public static final int OCB = 20;
  public static final int AND = 24;
  public static final int LT = 14;
  public static final int OR = 25;
  public static final int COMMA = 27;
  public static final int ORB = 18;
  public static final int PLUS = 30;
  public static final int IF = 2;
  public static final int ID = 38;
  public static final int CSB = 22;
  public static final int DOT = 17;
  public static final int LE = 15;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int RETURN = 7;
  public static final int TRUE = 9;
  public static final int error = 1;
  public static final int EX = 29;
  public static final int SEMI_COLON = 26;
  public static final int NUMBER = 39;
  public static final int MOD = 35;
  public static final int BREAK = 6;
  public static final int VOID = 11;
  public static final int INVALID_ESCAPE_CHARACTER = 37;
  public static final int EQ = 32;
  public static final int TIMES = 41;
  public static final int CCB = 21;
  public static final int ELSE = 5;
  public static final int EQQ = 16;
  public static final int WHILE = 3;
  public static final int CRB = 19;
  public static final int NE = 28;
  public static final int STRING = 36;
  public static final int FALSE = 10;
  public static final int GT = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "WHILE",
  "BOOLEAN",
  "ELSE",
  "BREAK",
  "RETURN",
  "INT",
  "TRUE",
  "FALSE",
  "VOID",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQQ",
  "DOT",
  "ORB",
  "CRB",
  "OCB",
  "CCB",
  "CSB",
  "OSB",
  "AND",
  "OR",
  "SEMI_COLON",
  "COMMA",
  "NE",
  "EX",
  "PLUS",
  "MINUS",
  "EQ",
  "DIVIDE",
  "STAR",
  "MOD",
  "STRING",
  "INVALID_ESCAPE_CHARACTER",
  "ID",
  "NUMBER",
  "SEMI",
  "TIMES",
  "UMINUS",
  "LPAREN",
  "RPAREN"
  };
}

